Clusters:
  - Input:
      Kafka:
        Name: go-stash
        Log:
          Mode: file
        Brokers:
          - "122.43.32.71:9092"
        Topics:
          - trajectory
        Group: stash
        Conns: 3
        Consumers: 10
        Processors: 60
        MinBytes: 1048576
        MaxBytes: 10485760
        Offset: first
    Output:
      ElasticSearch:
        Hosts:
          - "http://122.43.32.71:9200"
        Index: "trajectory-{{yyyy.MM.dd}}"
        MaxChunkBytes: 5242880
        GracePeriod: 10s
        Compress: false
        TimeZone: UTC
        UserName: "elastic"
        PassWord: "z123456"
LogConf:
  Level: info
  Path: logs
  Mode: file